wandb_version: 1

batch_size:
  desc: null
  value: 24
learning_rate:
  desc: null
  value: 5.0e-05
weight_decay:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 100
max_input_length:
  desc: null
  value: 512
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.7
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698131807.21395
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 16
      - 23
      4: 3.11.4
      5: 0.15.7
      6: 4.31.0
      8:
      - 4
      - 5
