
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Daniel Reichenpfader", email = "daniel.reichenpfader@bfh.ch"},
]
dependencies = [
    "torch>=2.0.1",
    "transformers>=4.30.2",
    "smaragd-shared-python @ git+https://${GITHUB_ACCESS_TOKEN}@github.com/innosuisse-smaragd/smaragd-shared-python.git@v2.1.0"
]
requires-python = ">=3.11"

[tool.pdm.dev-dependencies]
dev = [
    "jupyter>=1.0.0",
]
