
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Daniel Reichenpfader", email = "daniel.reichenpfader@bfh.ch"},
]
dependencies = [
    "torch>=2.0.1",
    "transformers>=4.30.2",
]
requires-python = ">=3.11"
